name: Update README with Latest Users

on:
  issues:
    types: [opened]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get issue data
      id: issue_data
      run: |
        echo "USER_NAME=${{ github.actor }}" >> $GITHUB_ENV
        echo "USER_AVATAR=${{ github.actor }}_avatar" >> $GITHUB_ENV
        echo "USER_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

    - name: Update README file
      run: |
        #Fetch current README
        sed -i '/<!--START_SECTION:users-->/, /<!--END_SECTION:users-->/d' README.md

        #Add the new user to the top of the list
        echo "| [${{ env.USER_NAME }}](https://github.com/${{ env.USER_NAME }}) | <img src=\"https://avatars.githubusercontent.com/${{ env.USER_NAME }}\" width=\"30\" height=\"30\" /> | ${{ env.USER_DATE }} |" >> README.md

        #Move last user to older section if more than 3 users exist
        awk '/<!--START_SECTION:users-->/ { print; users++; next } { if (users >= 3) print "<details><summary>Older users</summary>" } { print } /<!--END_SECTION:users-->/ { print "</details>"; }' README.md > README.md.temp && mv README.md.temp README.md

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with new user"
        git push
