name: Update README with Latest Users

on:
  issues:
    types: [opened]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Add initial reaction
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/reactions" \
          -d '{"content":"eyes"}'
        echo "originalTitle=false" >> $GITHUB_ENV  

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check issue title
      if: ${{ startsWith(github.event.issue.title, 'Submit yourself') }}
      run: |
        echo "originalTitle=true" >> $GITHUB_ENV

    - name: Get issue data
      run: |
        echo "USER_NAME=${{ github.actor }}" >> $GITHUB_ENV
        echo "USER_AVATAR=https://avatars.githubusercontent.com/${{ github.actor }}" >> $GITHUB_ENV
        echo "USER_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

    - name: Check for duplicates in README
      id: check_duplicates
      run: |
        if grep -q "\[${{ env.USER_NAME }}\](https://github.com/${{ env.USER_NAME }})" README.md; then
          echo "duplicate=true" >> $GITHUB_ENV
        else
          echo "duplicate=false" >> $GITHUB_ENV
        fi

    - name: Update README with latest user
      if: ${{ env.duplicate == 'false' }}
      run: |
        new_user_row="| [${{ env.USER_NAME }}](https://github.com/${{ env.USER_NAME }}) | <img src=\"${{ env.USER_AVATAR }}\" width=\"30\" height=\"30\" /> | ${{ env.USER_DATE }} |"

        awk -v new_user_row="$new_user_row" '
        BEGIN { 
          inside_users = 0
          inside_old = 0
          user_count = 0
          header_printed = 0
        }

        /<!--START_SECTION:users-->/ {
          print $0
          inside_users = 1
          if (!header_printed) {
            print "| Name | Profile Picture | Date |"
            print "| ---- | ---------------- | ---- |"
            header_printed = 1
          }
          print new_user_row
          next
        }

        inside_users && /^\|.*\|.*\|.*\|$/ && !/\| Name \|/ && !/\| ---- \|/ {
          user_count++
          if (user_count <= 2) {
            print $0
          } else {
            old_user = $0
          }
          next
        }

        /<!--END_SECTION:users-->/ {
          print $0
          inside_users = 0
          next
        }

        /<details>/ || /<summary>/ {
          print $0
          next
        }

        /<!--START_SECTION:old_users-->/ {
          print $0
          inside_old = 1
          print "| Name | Profile Picture | Date |"
          print "| ---- | ---------------- | ---- |"
          if (user_count > 2) {
            print old_user
          }
          next
        }

        inside_old && /^\|.*\|.*\|.*\|$/ && !/\| Name \|/ && !/\| ---- \|/ {
          print $0
          next
        }

        /<!--END_SECTION:old_users-->/ {
          print $0
          inside_old = 0
          next
        }

        !/\| Name \|/ && !/\| ---- \|/ {
          print $0
        }
        ' README.md > README.temp.md && mv README.temp.md README.md

    - name: Commit and push changes
      if: ${{ env.duplicate == 'false' }}
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with new user"
        git push

    - name: Close issue with a comment
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        COMMENT_BODY=$(if [ "${{ env.originalTitle }}" == "false" ]; then echo "Why tf did you change the title of the issue?"; else echo "Good job 👍"; fi)

        SECOND_COMMENT_BODY=$(if [ "${{ env.duplicate }}" == "true" ]; then echo "You are already on the list."; else echo "You have been added! Visit https://github.com/max1mde to see you there."; fi)


        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d "{\"body\":\"$SECOND_COMMENT_BODY\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments
        
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d "{\"body\":\"$COMMENT_BODY\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments

        curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER \
          -d '{"state":"closed"}'
